# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82fc7f99bc521fa519faf10a50d48fc98355a47c9ab812a3f24e84ba6d9a94c3eb651218bd5fddc215e733775ef3154191cda3c961f900709cd8cc1f184486ee

test:
  secret_key_base: 26c0ae9f01749ae238bd6e4d089b36f1e2c48ab870e111bbcda743879c0a3f583784a1a5c4b91bdf5b0b70de34e489625fea07c8053301ad77f3ee0e7a57b759

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
